### ISSUE TITLE
消息传递问题

### ISSUE THREAD

**Issue by Licarey** [simplezhli/Saber#1]
你好 请问demo中MainActivity怎么监听fragment数据改变

**Comment by simplezhli** [comment]
请查看最新master分支的TestActivity，MainActivity不能监听其他Activity的Fragment数据改变。只能监听自身Fragment数据改变。

**Comment by Licarey** [comment]
liveData会有这个限制吗？只要target不同就行吧 我看源码 只有销毁的时候 才会从callback集合中移除

**Comment by Licarey** [comment]
如果一个Observer的生命周期处于STARTED或RESUMED状态，那么LiveData将认为这个Observer处于活跃状态。 LiveData仅通知活跃的Observer去更新UI。 非活跃状态的Observer，即使订阅了LiveData，也不会收到更新的通知。是这个原因吧 MainActivity处于pause状态 所以监听不到 ？？？

**Comment by simplezhli** [comment]
这个框架是ViewModel与LiveData的结合使用，ViewModelStore是每一个Activity或Fragment都有一个，用于储存VireModel。所以之间的ViewModel不互通。你的这种需求，可以继承LiveData实现数据共享。本框架咱不支持。
