### ISSUE TITLE
有关@LiveData的问题

### ISSUE THREAD

**Issue by imyyq-star** [simplezhli/Saber#2]
Hi，发现一些可改进的，如下：

1、@LiveData只能生成MutableLiveData类型的，但是很多时候也会需要MediatorLiveData类型的，建议加入。
2、LiveDateType是不是拼写错了？会不会是LiveDataType

**Comment by simplezhli** [comment]
@imyyq-star 感谢指出拼写错误，疏忽了。。。关于MediatorLiveData已有计划加入，敬请期待！

**Comment by simplezhli** [comment]
@imyyq-star 可以升级至0.2.1

**Comment by imyyq-star** [comment]
不对呀，生成报错了，

`错误: 无法将类 MediatorLiveData<T>中的方法 addSource应用到给定类型;
    this.mClassSchedule.addSource(source, onChanged);
                       ^
  需要: LiveData<S#1>,Observer<S#1>
  找到: LiveData<S#2>,Observer<CAP#1>
  原因: 推断类型不符合等式约束条件
    推断: CAP#1
    等式约束条件: CAP#1,S#2
  其中, S#1,S#2,T是类型变量:
    S#1扩展已在方法 <S#1>addSource(LiveData<S#1>,Observer<S#1>)中声明的Object
    S#2扩展已在方法 <S#2>addSource(LiveData<S#2>,Observer<? super S#2>)中声明的Object
    T扩展已在类 MediatorLiveData中声明的Object
  其中, CAP#1是新类型变量:
    CAP#1从? super S#2的捕获扩展Object 超 S#2
1 个错误
1 个警告`




生成的代码是：

`public <S> void addSource(@NonNull LiveData<S> source, @NonNull Observer<? super S> onChanged)`


正确的是：

`public <S> void addSource(@NonNull LiveData<S> source, @NonNull Observer<S> onChanged)`

**Comment by simplezhli** [comment]
@imyyq-star  检查了一下发现了问题，这个android与androidx之间的源码不一致导致的，androidx为`Observer<? super S> onChanged`，我明天在修复一下这个问题，感谢！

**Comment by simplezhli** [comment]
@imyyq-star 忙里偷个闲改好了，你再试试。升级至0.2.2  😏

**Comment by imyyq-star** [comment]
ok，没问题了，赞

**Comment by imyyq-star** [comment]
今天又发现一个问题。如果MediatorLiveData有两个的话，自动生成的removeSource和addSource会冲突

**Comment by simplezhli** [comment]
@imyyq-star 这个问题昨天已经解决了，不过还没有打包。稳定下来了我在统一升级。

**Comment by imyyq-star** [comment]
Saber.bind(this);
这一句如果放在父类中，但是子类并没有使用到ViewModel和LiveData，会有影响吗？比如产生多余的对象什么的。因为我想放在BaseActivity中

**Comment by simplezhli** [comment]
@imyyq-star 这里的内部实现和`ButterKnife`是一样的，当找不到生成的"XXX_Providers"类时，直接返回一个空实现，可放心使用：

```java
    public static UnBinder bind(@NonNull Object target) {
        return createBinding(target);
    }

    private static UnBinder createBinding(@NonNull Object target) {
        Class<?> targetClass = target.getClass();
        Constructor<? extends UnBinder> constructor = findBindingConstructorForClass(targetClass);

        if (constructor == null) {
            return UnBinder.EMPTY;
        }
   }
```

**Comment by simplezhli** [comment]
@imyyq-star 可以升级至0.2.3，[更新说明点击](https://github.com/simplezhli/Saber/releases/tag/0.2.3)。
注意依赖的saber都变为了小写：`com.github.simplezhli.saber:saber-api:xxx`
