### ISSUE TITLE
关于注解生成和留存的问题

### ISSUE THREAD

**Issue by imyyq-star** [simplezhli/Saber#3]
Hi 兄弟，我又来了。

1、我发现@LiveData注解的Retention是Class的，这样会导致即使混淆打包后，反编译的@LiveData注解也会留存在字节码文件中。@LiveData的作用我理解的是在编译器生成相关和绑定代码，所以是否没有必要留存在字节码中？

2、使用@LiveData后总是要Make Module，是否可以Sync就可以生成相关代码？

3、我在TestViewModel中，使用@LiveData注解后，生成的是TestViewModelViewModel，后缀重复，是否可以判断下后缀？

以上，是我使用以来的总结。望回复。

**Comment by simplezhli** [comment]
@imyyq-star 
第一点：你说的是对的，不过我发现在kotlin环境中使用SOURCE无法正常工作。如果你需要处理，我记得有个框架可以实现，不过我暂时找不到了。
第二点：我暂时不知道如何实现，因为sync操作是对gradle的处理。如果你有好的方案可以告诉我。
第三点：我可以处理下，其实本意是希望标注到对应的类上的，所以强制添加了后缀。

**Comment by simplezhli** [comment]
@imyyq-star 问题三已经处理，请升级至[0.2.4](https://github.com/simplezhli/Saber/releases/tag/0.2.4)
