### ISSUE TITLE
Android Studio 4.0 无法使用

### ISSUE THREAD

**Issue by imyyq-star** [simplezhli/Saber#6]
在 AS 4.0 中无法生成相关的类，我克隆源代码到本地也运行不起来，相关的生成类比如 SeekBarViewModel 都没有生成，Clean，Build 都没用，是否只能低版本的 AS 才可以呢？

**Comment by simplezhli** [comment]
我试了下，直接跑代码没问题。看是不是gradle版本问题。

**Comment by simplezhli** [comment]
尝试 0.2.6，看是否还有问题。
